name: l33t-c0d3-t1m3-wkflw
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  l33t-c0d3-t1m3-job:
    runs-on: ubuntu-latest
    environment: l33t-c0d3-t1m3
    steps:
      - uses: actions/checkout@master
      - name: Update l33t-c0d3-t1m3 stats
        uses: ./../../.@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
