name: l33t-c0d3-t1m3
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    environment: l33t-c0d3-t1m3
    steps:
      - uses: actions/checkout@master
      - name: Update l33t-c0d3-t1m3 stats
        uses: nickheyer/l33t-c0d3-t1m3@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
